version: '3'

services:
  pw-server:
    build: .cloud/docker
    image: laravel-pw
    depends_on:
      - mysql
      - redis
    volumes:
      - ./:/application:cached

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlpass
      - MYSQL_DATABASE=laravel_pw
    volumes:
      - ./storage/tmp/db:/var/lib/mysql:cached
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_USER: root
      PMA_PASSWORD: mysqlpass
      PMA_HOSTS: mysql
    ports:
      - 8080:80

  nginx:
    image: nginx
    ports:
      - "8000:8000"
    volumes:
      - .cloud/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:cached
      - ./:/application:cached
    depends_on:
      - pw-server

  redis:
    image: redis
    ports:
      - "6379:6379"
